web/urls.py
from django.urls import path

from . import views


app_name = "web"

urlpatterns = [
    path("", views.index, name="index"),
    path("football_academy/", views.football_academy, name="football_academy"),
    path("programs/<slug>/", views.programs, name="programs"),
    path("contact", views.contact, name="contact"),
    path("magazine", views.magazine, name="magazine"),
    path("magazine_detail", views.magazine_detail, name="magazine_detail"),
]

xluae/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views.generic import TemplateView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("web.urls", namespace="web")),
    path(
        "sitemap.xml",
        TemplateView.as_view(template_name="sitemap.xml", content_type="text/xml"),
    ),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
    path("tinymce/", include("tinymce.urls")),
    *static(settings.STATIC_URL, document_root=settings.STATIC_ROOT),
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]

admin.site.site_header = "XLUAE Administration"
admin.site.site_title = "XLUAE Admin Portal"
admin.site.index_title = "Welcome to XLUAE Admin Portal"

web/models.py
from django.db import models
from tinymce.models import HTMLField
from versatileimagefield.fields import PPOIField
from versatileimagefield.fields import VersatileImageField


class WeOffer(models.Model):
    heading = models.CharField(max_length=255)
    description = HTMLField(null=True, blank=True)
    order = models.CharField(max_length=10, null=True, blank=True)

    class Meta:
        ordering = ["order"]
        verbose_name_plural = "We Offer"

    def __str__(self):
        return str(self.heading)


class EducationalPrograms(models.Model):
    course_name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=300, unique=True)
    image = VersatileImageField("Image", upload_to="Course/", ppoi_field="ppoi")
    ppoi = PPOIField("Image PPOI")
    description = HTMLField(null=True, blank=True)

    class Meta:
        verbose_name_plural = "Educational Programs"

    def __str__(self):
        return str(self.course_name)


class Contact(models.Model):
    name = models.TextField()
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return self.name


class Feature(models.Model):
    name = models.CharField(max_length=255)
    image = VersatileImageField("Image", upload_to="Feature/", ppoi_field="ppoi")
    ppoi = PPOIField("Image PPOI")
    order = models.CharField(max_length=10, null=True, blank=True)

    class Meta:
        ordering = ["order"]

    def __str__(self):
        return str(self.name)


class SocialMedia(models.Model):
    platform = models.CharField(
        max_length=20,
        choices=[
            ("facebook", "Facebook"),
            ("twitter", "Twitter"),
            ("linkedin", "Linkedin"),
            ("instagram", "Instagram"),
        ],
    )

    link = models.URLField(null=True, blank=True)

    def __str__(self):
        return str(self.platform)


class Team(models.Model):
    name = models.CharField(max_length=255)
    image = VersatileImageField("Image", upload_to="Team/", ppoi_field="ppoi")
    ppoi = PPOIField("Image PPOI")
    role = models.CharField(max_length=255)
    order = models.CharField(max_length=10, null=True, blank=True)

    class Meta:
        ordering = ["order"]

    def __str__(self):
        return str(self.name)


from django.db import models

class Magazine(models.Model):
    image = models.ImageField(upload_to='media')
    name = models.CharField(max_length=100)
    month = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    

web/forms.py
from django import forms
from django.forms.widgets import EmailInput
from django.forms.widgets import Textarea
from django.forms.widgets import TextInput

from .models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        exclude = ()
        widgets = {
            "name": TextInput(
                attrs={
                    "type": "text",
                    "name": "name",
                    "class": "form-control",
                    "id": "contactFormFullName",
                    "placeholder": "Enter your full name",
                }
            ),
            "email": EmailInput(
                attrs={
                    "type": "email",
                    "class": "form-control",
                    "id": "contactFormEmail",
                    "placeholder": "Your Email*",
                    "name": "Enter your email address",
                }
            ),
            "message": Textarea(
                attrs={
                    "name": "message",
                    "class": "form-control",
                    "id": "exampleInputMessage1",
                    "placeholder": "Enter your message...",
                }
            ),
        }

web/views.py
import json

from django.http import HttpResponse
from django.shortcuts import render

from .forms import ContactForm
from .models import EducationalPrograms, Feature, Team, WeOffer, Magazine


def index(request):
    weoffers = WeOffer.objects.all()
    programs = EducationalPrograms.objects.all()

    form = ContactForm(request.POST or None, request.FILES or None)
    if request.method == "POST":
        if form.is_valid():
            data = form.save(commit=False)

            data.save()
            response_data = {
                "status": "true",
                "title": "Successfully Submitted",
                "message": "Thank You, Our Team Will Contact you Soon",
            }
        else:
            print(form.errors)
            response_data = {
                "status": "false",
                "title": "form2 validation error",
                "message": repr(form.errors),
            }
        return HttpResponse(
            json.dumps(response_data), content_type="application/javascript"
        )
    else:
        context = {"weoffers": weoffers, "programs": programs, "form": form}
    return render(request, "web/index.html", context)


def football_academy(request):
    features = Feature.objects.all()
    teams = Team.objects.all()
    context = {"features": features, "teams": teams}
    return render(request, "web/football_academy.html", context)


def programs(request, slug):
    program_details = EducationalPrograms.objects.get(slug=slug)
    context = {"program_details": program_details}
    return render(request, "web/programs.html", context)


def contact(request):
    form = ContactForm(request.POST or None, request.FILES or None)
    if request.method == "POST":
        if form.is_valid():
            data = form.save(commit=False)

            data.save()
            response_data = {
                "status": "true",
                "title": "Successfully Submitted",
                "message": "Thank You, Our Team Will Contact you Soon",
            }
        else:
            print(form.errors)
            response_data = {
                "status": "false",
                "title": "form2 validation error",
                "message": repr(form.errors),
            }
        return HttpResponse(
            json.dumps(response_data), content_type="application/javascript"
        )
    else:
        context = {"form": form}
    return render(request, "web/contact.html", context)

def magazine(request):
    magazines = Magazine.objects.all()
    return render (request, 'web/magazine.html', {'magazines': magazines})  

def magazine_detail(request):
    return render (request, 'web/magazine_detail.html')

templates/web/contact.html
<!DOCTYPE html>
<html class="no-js" lang="en">

<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>EXCEL - Educational Services</title>
    <link rel="icon" href="{% static 'web/images/favicon.png' %}" type="image/x-icon" />
    <meta name="description" content="Excel Educational Services">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSS Dependencies -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'web/css/excel.css' %}">
    <link rel="stylesheet" href="{% static 'web/css/excel-extras.css' %}">
</head>

<body class="excel-landing-page">
    <!-- Welcome Section -->
    <div class="program d-flex justify-content-center flex-column">
        <div class="container">
            <!-- Navigation -->
            <nav class="navbar navbar-expand-lg navbar-dark pt-4 px-0">
                <a class="navbar-brand" href="/">
                    <img src="{% static 'web/images/excel.png' %}" class="mr-2" alt="Excel">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                    aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="/">Home
                                <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link" href="{% url 'web:football_academy' %}">Football Academy</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href=""
                                id="navbarDropdownMenuLink-7" data-toggle="dropdown" aria-haspopup="true"
                                aria-expanded="false">
                                Edu Programs
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                {% for i in programs %}
                                <a class="dropdown-item" href="{% url 'web:programs' i.slug %}">{{i.course_name}}</a>
                                {% endfor %}
                            </div>
                        </li>
                        

                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'web:contact' %}">Contacts</a>
                        </li>

                    </ul>
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            {% for link in social %}
                            <a class="socio_icon" href="#"><i class="fa fa-{{link.platform}}"></i></a>
                            {% endfor %}
                        </li>

                    </ul>
                </div>
            </nav>
            <!-- / Navigation -->
        </div> <!-- .container -->

        <!-- Inner Wrapper -->
        <div class="inner-wrapper mt-auto mb-auto container">
            <div class="row">
                <div class="col-md-7">
                    <h1 class="welcome-heading display-4 text-white">Contact Us</h1>
                    
                </div>
            </div>
        </div>
        <!-- / Inner Wrapper -->
    </div>
    <!-- / Welcome Section -->


    <!-- Contact Section -->
    <div id="contact" class="contact section-invert py-4">
       
        <div class="container py-4 mt-5">
            <div class="row">

                <div class="col-md-8 col-sm-12">
                    <div class="row">
                        <div class="contact-form  p-4 mb-4 card">
                            <form method="post" class="form contact" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="row">
                                <div class="col-md-6 col-sm-12">
                                  <div class="form-group">
                                    <label for="contactFormFullName">Full Name</label>
                                    {{form.name}}
                                  </div>
                                </div>
                                <div class="col-md-6 col-sm-12">
                                  <div class="form-group">
                                    <label for="contactFormEmail">Email address</label>
                                    {{form.email}}
                                  </div>
                                </div>
                              </div>
                              <div class="row">
                                <div class="col">
                                  <div class="form-group">
                                    <label for="exampleInputMessage1">Message</label>
                                    {{form.message}}
                                  </div>
                                </div>
                              </div>
                              <button class="btn btn-primary btn-pill d-flex ml-auto mr-auto" type="submit" value="Send Your Message"><span>Send Your Message</span></button>
                            </form>
                          </div>
                    </div>
                </div>




                <div class="col-md-4 col-sm-12">
                    

                           
                            
                                <div class="feature py-4 d-flex">
                                    <div class="icon text-primary mr-3"><i class="fa fa-whatsapp"></i></div>
                                    <div class="mt-3">
                                      <p>+971 50 8489 313</p>
                                    </div>
                                </div>

                                <div class="feature py-4 d-flex">
                                    <div class="icon text-primary mr-3"><i class="fa fa-envelope-o"></i></div>
                                    <div class="mt-3">
                                      <p>muhsi@xluae.com</p>
                                    </div>
                                </div>

                                <div class="feature py-4 d-flex">
                                    <div class="icon text-primary mr-3"><i class="fa fa-map-marker"></i></div>
                                    <div class="mt-3">
                                      <p>Dubai - Silicon Oasis Authority</p>
                                    </div>
                                </div>
                                    

                   
                </div>
                

            </div>
        </div>
    </div>
    <!-- / Contact Section -->

    <!-- Footer CTA -->
    <div class="footer-cta bg-dark">
        <div class="container mt-5">
            <div class="py-3">

                <div class="share d-table ml-auto mr-auto my-3">
                    <a href="#" class="btn btn-pill btn-primary mr-4 mb-2" title="Share Shards on Twitter">
                        <i class="fa fa-whatsapp mr-1"></i> +971 50 8489 313</a>
                    <a href="#" class="btn btn-pill btn-primary mr-4 mb-2" title="Email">
                        <i class="fa fa-envelope-o mr-1"></i> muhsi@xluae.com</a>
                    <a href="#" class="btn btn-pill btn-primary mr-4 mb-2" title="Share on LinkedIn">
                        <i class="fa fa-map-marker mr-1"></i> Dubai - Silicon Oasis Authority</a>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer Section -->
    <footer class="main-footer py-5">
        <p class="text-muted text-center small p-0 mb-4">&copy; Copyright 2017 — Excel Educational Services</p>
        <div class="social d-table ml-auto mr-auto">
            {% for link in social %}
            <a class="twitter mx-3 h4" href="#" target="_blank">
                <i class="fa fa-{{link.platform}}"></i>
            </a>
            {% endfor %}

           
        </div>
    </footer>
    <!-- / Footer Section -->

    <!-- JavaScript Dependencies -->
    <!-- JavaScript Dependencies -->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9.15.3/dist/sweetalert2.all.min.js"></script>
    <script src="{% static 'web/js/form.js' %}"></script>
</body>

</html>

templates/web/magazine.html
<!DOCTYPE html>
<html class="no-js" lang="en">

<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>EXCEL - Educational Services</title>
    <link rel="icon" href="{% static 'web/images/favicon.png' %}" type="image/x-icon" />
    <meta name="description" content="Excel Educational Services">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSS Dependencies -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'web/css/excel.css' %}">
    <link rel="stylesheet" href="{% static 'web/css/excel-extras.css' %}">
    <link rel="stylesheet" href="{% static 'web/css/magazine.css' %}">
</head>

<body class="excel-landing-page">
    <!-- Welcome Section -->
    <div class=" d-flex justify-content-center flex-column" style="background-color: black;">
        <div class="container">
            <!-- Navigation -->
            <nav class="navbar navbar-expand-lg navbar-dark pt-4 px-0">
                <a class="navbar-brand" href="/">
                    <img src="{% static 'web/images/excel.png' %}" class="mr-2" alt="Excel">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                    aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="/">Home
                                <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'web:football_academy' %}">Football Academy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'web:magazine' %}">Edu Magazine</a>
                          </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href=""
                                id="navbarDropdownMenuLink-7" data-toggle="dropdown" aria-haspopup="true"
                                aria-expanded="false">
                                Edu Programs
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                {% for i in programs %}
                                <a class="dropdown-item" href="{% url 'web:programs' i.slug %}">{{i.course_name}}</a>
                                {% endfor %}
                            </div>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'web:contact' %}">Contacts</a>
                        </li>

                    </ul>
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            {% for link in social %}
                            <a class="socio_icon" href="#"><i class="fa fa-{{link.platform}}"></i></a>
                            {% endfor %}
                        </li>

                    </ul>
                </div>
            </nav>
            <!-- / Navigation -->
        </div> <!-- .container -->

        
<!-- slider-start -->
    <div class="slider-area pos-relative">
        <div class="slider-active">
            <div class="single-slider slider-height d-flex align-items-center justify-content-center" style="background-image: url(https://wphix.com/template/sikkha-prv/sikkha/img/slider/slider_bg_1.jpg);">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-9 col-md-12">
                            <div class="slider-content slider-content-2">
                                <h1 class="white-color f-700" data-animation="fadeInUp" data-delay=".2s"><span>EDU MAGAZINW</span><br>Eduara University</h1>
                                <p data-animation="fadeInUp" data-delay=".4s">Sorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod tempor <br> incididunt ut labore et dolore magna aliqua enim ad minime.</p>
                                <button class="theme-btn" data-animation="fadeInUp" data-delay=".6s"><span class="btn-text"><a href="{% url 'web:magazine_detail' %}">Read Online</a></span></button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
           
        </div>
    </div>
    <!-- slider-end -->

    <div class=" d-flex justify-content-center flex-column" style="background-color: black;">
        <section style="background-color: white">
          <div class="testimonials section py-4">
            <div class="container py-5">
          <div class="row">
            {% for magazine in magazines %}
            <div class="col-lg-3 col-md-6 col-6 mb-2">
                <div class="card">
                    <img src="{{magazine.image.url}}" class="card-img-top" alt="img">
                    <div class="card-body">
                        <h5 class="card-title">{{ magazine.name }}</h5>
                        <p class="card-text" style="font-weight: bold;">{{ magazine.month }}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
    

          </div>
        </div>

    </section>


        <footer class="main-footer py-5">
          <p class="text-muted text-center small p-0 mb-4">&copy; Copyright 2017 — Excel Educational Services</p>
          <div class="social d-table ml-auto mr-auto">
              {% for link in social %}
              <a class="twitter mx-3 h4" href="#" target="_blank">
                  <i class="fa fa-{{link.platform}}"></i>
              </a>
              {% endfor %}
  
             
          </div>
      </footer>
      <script>
        
      </script>
      <!-- / Footer Section -->
  
      <!-- JavaScript Dependencies -->
      <!-- JavaScript Dependencies -->
      <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9.15.3/dist/sweetalert2.all.min.js"></script>
      <script src="{% static 'web/js/form.js' %}"></script>
  </body>
  
  </html>

templates/web/magazine_detail.html
<!DOCTYPE html>
<html class="no-js" lang="en">

<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>EXCEL - Educational Services</title>
    <link rel="icon" href="{% static 'web/images/favicon.png' %}" type="image/x-icon" />
    <meta name="description" content="Excel Educational Services">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSS Dependencies -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'web/css/excel.css' %}">
    <link rel="stylesheet" href="{% static 'web/css/excel-extras.css' %}">
    <link rel="stylesheet" href="{% static 'web/css/magazine.css' %}">
</head>

<body class="excel-landing-page">
    <!-- Welcome Section -->
    <div class=" d-flex justify-content-center flex-column" style="background-color: black;">
        <div class="container">
            <!-- Navigation -->
            <nav class="navbar navbar-expand-lg navbar-dark pt-4 px-0">
                <a class="navbar-brand" href="/">
                    <img src="{% static 'web/images/excel.png' %}" class="mr-2" alt="Excel">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                    aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="/">Home
                                <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'web:football_academy' %}">Football Academy</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'web:magazine' %}">Edu Magazine</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href=""
                                id="navbarDropdownMenuLink-7" data-toggle="dropdown" aria-haspopup="true"
                                aria-expanded="false">
                                Edu Programs
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                {% for i in programs %}
                                <a class="dropdown-item" href="{% url 'web:programs' i.slug %}">{{i.course_name}}</a>
                                {% endfor %}
                            </div>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'web:contact' %}">Contacts</a>
                        </li>

                    </ul>
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            {% for link in social %}
                            <a class="socio_icon" href="#"><i class="fa fa-{{link.platform}}"></i></a>
                            {% endfor %}
                        </li>

                    </ul>
                </div>
            </nav>
            <!-- / Navigation -->
        </div> <!-- .container -->

        <section style="background-color: white">
          <div class="testimonials section py-4">
            <h3 class="section-title text-center mt-5">Books Lists </h3>
            <div class="container py-5">
          <div class="row">
            <div class="col-lg-3 col-md-6 col-6 mb-2">
                <div class="card">
                    <img src="{% static 'web/images/book.jpg' %}" class="card-img-top" alt="img">
                    <div class="card-body">
                        <h5 class="card-title">Book Name</h5>
                        <p class="card-text">17.09.2024</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-6 mb-2">
                <div class="card">
                    <img src="{% static 'web/images/book.jpg' %}" class="card-img-top" alt="img">
                    <div class="card-body">
                        <h5 class="card-title">Book Name</h5>
                        <p class="card-text">17.09.2024</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-6 mb-2">
                <div class="card">
                    <img src="{% static 'web/images/book.jpg' %}" class="card-img-top" alt="img">
                    <div class="card-body">
                        <h5 class="card-title">Book Name</h5>
                        <p class="card-text">17.09.2024</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-6 mb-2">
                <div class="card">
                    <img src="{% static 'web/images/book.jpg' %}" class="card-img-top" alt="img">
                    <div class="card-body">
                        <h5 class="card-title">Book Name</h5>
                        <p class="card-text">17.09.2024</p>
                    </div>
                </div>
            </div>
          </div>
        </div>

    </section>





        <footer class="main-footer py-5">
          <p class="text-muted text-center small p-0 mb-4">&copy; Copyright 2017 — Excel Educational Services</p>
          <div class="social d-table ml-auto mr-auto">
              {% for link in social %}
              <a class="twitter mx-3 h4" href="#" target="_blank">
                  <i class="fa fa-{{link.platform}}"></i>
              </a>
              {% endfor %}
  
             
          </div>
      </footer>
      <script>
        
      </script>
      <!-- / Footer Section -->
  
      <!-- JavaScript Dependencies -->
      <!-- JavaScript Dependencies -->
      <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9.15.3/dist/sweetalert2.all.min.js"></script>
      <script src="{% static 'web/js/form.js' %}"></script>
  </body>
  
  </html>